name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
      fail-fast: true
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'node20'

      - name: Install Deps
        run: npm install

      - name: Verify formatting
        run: npm run format:check

      - name: Run Test
        if: matrix.os != 'windows-latest'
        run: npm run test